// Builds the offline CodeMirror HTML for the editor WebView.
//
// Steps:
//   1. esbuild bundles components/editor/cm-source.js (CM6 + Java lang +
//      search/autocomplete/commands) into a single minified IIFE string.
//   2. We inline that bundle into components/editor/codemirror.html (replacing
//      the BUNDLE_PLACEHOLDER comment) producing one self-contained HTML doc.
//   3. We emit components/editor/editorHtml.generated.ts exporting that HTML as
//      a string, so the React component imports it as a normal TS module — no
//      metro asset config, no extra deps, no runtime network fetch.
//
// Run via: npm run build:editor
import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = resolve(root, "components/editor/cm-source.js");
const templatePath = resolve(root, "components/editor/codemirror.html");
const outPath = resolve(
  root,
  "components/editor/editorHtml.generated.ts"
);

const result = await build({
  entryPoints: [sourcePath],
  bundle: true,
  minify: true,
  format: "iife",
  target: "es2020",
  write: false,
  logLevel: "info",
});

const bundleJs = result.outputFiles[0].text;

let template = readFileSync(templatePath, "utf8");
const placeholder = "<!-- BUNDLE_PLACEHOLDER -->";
const script = `<script>\n${bundleJs}\n</script>`;
if (template.includes(placeholder)) {
  template = template.replace(placeholder, script);
} else {
  template = template.replace("</body>", `${script}\n  </body>`);
}

// Escape backticks and ${ for safe embedding in a TS template literal.
const escaped = template.replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const ts = `// AUTO-GENERATED by scripts/build-editor.mjs — do not edit by hand.
// Regenerate with: npm run build:editor
// Contains the full offline CodeMirror 6 HTML (bundle inlined) as a string.
export const EDITOR_HTML = \`${escaped}\`;
`;

writeFileSync(outPath, ts);
console.log(
  `[build:editor] wrote ${outPath} (${(ts.length / 1024).toFixed(1)} KB)`
);
